In [1]:
#import modules
import os
import glob
import pandas as pd
#list all csv files only
csv_files = glob.glob('T3_AIR*.{}'.format('csv'))
csv_files

['T3_AIR_CARRIER_SUMMARY_AIRPORT_ACTIVITY_2019.csv',
 'T3_AIR_CARRIER_SUMMARY_AIRPORT_ACTIVITY_2020.csv']

In [2]:
df_concat = pd.concat([pd.read_csv(f) for f in csv_files ], ignore_index=True)
df_concat

,OP_UNIQUE_CARRIER,CARRIER_NAME,ORIGIN_AIRPORT_ID,SERVICE_CLASS,REV_ACRFT_DEP_PERF_510,REV_PAX_ENP_110
0,04Q,Tradewind Aviation,15024,K,10.0,39.0
1,04Q,Tradewind Aviation,14843,K,677.0,3649.0
2,04Q,Tradewind Aviation,10257,V,4.0,6.0
3,04Q,Tradewind Aviation,15323,V,1.0,3.0
4,04Q,Tradewind Aviation,10158,V,1.0,2.0
...,...,...,...,...,...,...
33505,ZW,Air Wisconsin Airlines Corp,11721,K,119.0,4463.0
33506,ZW,Air Wisconsin Airlines Corp,10469,K,160.0,5095.0
33507,ZW,Air Wisconsin Airlines Corp,12884,K,159.0,5165.0
33508,ZW,Air Wisconsin Airlines Corp,15380,K,118.0,4011.0
33509,ZW,Air Wisconsin Airlines Corp,15624,K,4.0,91.0

In [3]:
df_concat.to_csv("C:\\Users\\sachi\\Downloads\\archive (5)\\raw_data\\Ontimerepclean\\merged_T3_AIR_CARRIER_SUMMARY_AIRPORT_ACTIVITY.csv")