In [1]:
#import pandas module
import pandas as pd
#read the csv file into a dataframe
df = pd.read_csv("C:\\Users\\sachi\\Downloads\\archive (5)\\raw_data\\Ontimerepclean\\ontimerep0119.csv")
df

,Unnamed: 0,DATE,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,...,CANCELLATION_CODE,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,209215,2019-01-01,2,WN,N739GB,2147,11259,DAL,"Dallas, TX",10140,...,NaN,105.0,110.0,580.0,3,NaN,NaN,NaN,NaN,NaN
1,414822,2019-01-01,2,OO,N679SA,5046,14543,RKS,"Rock Springs, WY",11292,...,NaN,76.0,94.0,260.0,2,0.0,0.0,18.0,0.0,1.0
2,553640,2019-01-01,2,YV,N83329,6016,10713,BOI,"Boise, ID",12266,...,NaN,228.0,216.0,1482.0,6,NaN,NaN,NaN,NaN,NaN
3,201914,2019-01-01,2,AA,N102NN,1140,10721,BOS,"Boston, MA",12478,...,NaN,78.0,64.0,187.0,1,NaN,NaN,NaN,NaN,NaN
4,31752,2019-01-01,2,AA,N103NN,33,12478,JFK,"New York, NY",12892,...,NaN,414.0,438.0,2475.0,10,0.0,0.0,20.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583980,343879,2019-01-31,4,F9,N205FR,685,13204,MCO,"Orlando, FL",11292,...,NaN,260.0,243.0,1546.0,7,0.0,0.0,0.0,0.0,28.0
583981,343878,2019-01-31,4,F9,N205FR,682,11292,DEN,"Denver, CO",13204,...,NaN,214.0,196.0,1546.0,7,0.0,0.0,0.0,0.0,36.0
583982,343877,2019-01-31,4,F9,N205FR,465,13487,MSP,"Minneapolis, MN",11292,...,NaN,146.0,121.0,680.0,3,0.0,0.0,0.0,0.0,18.0
583983,343883,2019-01-31,4,F9,N206FR,2041,14635,RSW,"Fort Myers, FL",12339,...,NaN,160.0,146.0,945.0,4,NaN,NaN,NaN,NaN,NaN
583984,515470,2019-01-31,4,WN,N203WN,990,12892,LAX,"Los Angeles, CA",10423,...,NaN,175.0,194.0,1242.0,5,18.0,0.0,19.0,0.0,20.0

In [1]:
#import the modules
#import os
#import pandas as pd
#read the path
#file_path = "C:\\Users\\sachi\\Downloads\\archive (5)\\raw_data\\Ontimerepclean"
#list all the files from the directory
#file_list = os.listdir(file_path)
#file_list

#import modules
import os
import glob
import pandas as pd
#list all csv files only
csv_files = glob.glob('ontimerep*19.{}'.format('csv'))
csv_files

['ontimerep0119.csv',
 'ontimerep0219.csv',
 'ontimerep0319.csv',
 'ontimerep0419.csv',
 'ontimerep0519.csv',
 'ontimerep0619.csv',
 'ontimerep0719.csv',
 'ontimerep0819.csv',
 'ontimerep0919.csv',
 'ontimerep1019.csv',
 'ontimerep1119.csv',
 'ontimerep1219.csv']

In [2]:
df_append = pd.DataFrame()
#append all files together
for file in csv_files:
            df_temp = pd.read_csv(file)
            df_append = df_append.append(df_temp, ignore_index=True)
df_append

C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_16848\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)

,Unnamed: 0,DATE,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,...,CANCELLATION_CODE,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,209215,2019-01-01,2,WN,N739GB,2147,11259,DAL,"Dallas, TX",10140,...,NaN,105.0,110.0,580.0,3,NaN,NaN,NaN,NaN,NaN
1,414822,2019-01-01,2,OO,N679SA,5046,14543,RKS,"Rock Springs, WY",11292,...,NaN,76.0,94.0,260.0,2,0.0,0.0,18.0,0.0,1.0
2,553640,2019-01-01,2,YV,N83329,6016,10713,BOI,"Boise, ID",12266,...,NaN,228.0,216.0,1482.0,6,NaN,NaN,NaN,NaN,NaN
3,201914,2019-01-01,2,AA,N102NN,1140,10721,BOS,"Boston, MA",12478,...,NaN,78.0,64.0,187.0,1,NaN,NaN,NaN,NaN,NaN
4,31752,2019-01-01,2,AA,N103NN,33,12478,JFK,"New York, NY",12892,...,NaN,414.0,438.0,2475.0,10,0.0,0.0,20.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422032,188882,2019-12-31,2,DL,N935DN,635,14100,PHL,"Philadelphia, PA",10397,...,NaN,147.0,131.0,666.0,3,NaN,NaN,NaN,NaN,NaN
7422033,188883,2019-12-31,2,DL,N112DU,636,12266,IAH,"Houston, TX",12953,...,NaN,197.0,191.0,1416.0,6,NaN,NaN,NaN,NaN,NaN
7422034,188884,2019-12-31,2,DL,N988DN,644,10994,CHS,"Charleston, SC",10397,...,NaN,80.0,69.0,259.0,2,NaN,NaN,NaN,NaN,NaN
7422035,188867,2019-12-31,2,DL,N829NW,596,13830,OGG,"Kahului, HI",14869,...,NaN,360.0,368.0,2935.0,11,NaN,NaN,NaN,NaN,NaN
7422036,625762,2019-12-31,2,B6,N907JB,862,14843,SJU,"San Juan, PR",10721,...,NaN,249.0,231.0,1674.0,7,NaN,NaN,NaN,NaN,NaN

In [3]:
df_append.to_csv("C:\\Users\\sachi\\Downloads\\archive (5)\\raw_data\\Ontimerepclean\\merged-ontimerep2019.csv")